sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: TOOLSET=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: TOOLSET=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: TOOLSET=g++-5

# Get newish CMake binary
before_script:
  - wget https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz
  - tar xfz cmake-3.7.1-Linux-x86_64.tar.gz
  - rm cmake-3.7.1-Linux-x86_64.tar.gz

# Prepare build
before_script:
  - export PATH="${PWD}/cmake-3.7.1-Linux-x86_64/bin:${PATH}"
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET

script:
  - make VERBOSE=1
  - ./KvasirTest
