sudo: false
language: cpp

addons:
  apt:
    packages:
      - curl

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: TOOLSET=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: TOOLSET=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: TOOLSET=g++-5

# Get newish CMake binary and prepare build
before_script:
  - curl https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz -o cmake.tar.gz
  - tar xfz cmake.tar.gz
  - rm cmake.tar.gz
  - mv cmake-* cmake
  - export PATH="${PWD}/cmake/bin:${PATH}"
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET

script:
  - make VERBOSE=1
  - make test
